/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
library mapd.src.t_datum_type;

class TDatumType {
  static const int SMALLINT = 0;
  static const int INT = 1;
  static const int BIGINT = 2;
  static const int FLOAT = 3;
  static const int DECIMAL = 4;
  static const int DOUBLE = 5;
  static const int STR = 6;
  static const int TIME = 7;
  static const int TIMESTAMP = 8;
  static const int DATE = 9;
  static const int BOOL = 10;
  static const int INTERVAL_DAY_TIME = 11;
  static const int INTERVAL_YEAR_MONTH = 12;

  static final Set<int> VALID_VALUES = new Set.from([
    SMALLINT
    , INT
    , BIGINT
    , FLOAT
    , DECIMAL
    , DOUBLE
    , STR
    , TIME
    , TIMESTAMP
    , DATE
    , BOOL
    , INTERVAL_DAY_TIME
    , INTERVAL_YEAR_MONTH
  ]);
  static final Map<int, String> VALUES_TO_NAMES = {
    SMALLINT: 'SMALLINT'
    , INT: 'INT'
    , BIGINT: 'BIGINT'
    , FLOAT: 'FLOAT'
    , DECIMAL: 'DECIMAL'
    , DOUBLE: 'DOUBLE'
    , STR: 'STR'
    , TIME: 'TIME'
    , TIMESTAMP: 'TIMESTAMP'
    , DATE: 'DATE'
    , BOOL: 'BOOL'
    , INTERVAL_DAY_TIME: 'INTERVAL_DAY_TIME'
    , INTERVAL_YEAR_MONTH: 'INTERVAL_YEAR_MONTH'
  };
}
