/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
library mapd.src.t_device_type;

class TDeviceType {
  static const int CPU = 0;
  static const int GPU = 1;

  static final Set<int> VALID_VALUES = new Set.from([
    CPU
    , GPU
  ]);
  static final Map<int, String> VALUES_TO_NAMES = {
    CPU: 'CPU'
    , GPU: 'GPU'
  };
}
