/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
library mapd.src.t_encoding_type;

class TEncodingType {
  static const int NONE = 0;
  static const int FIXED = 1;
  static const int RL = 2;
  static const int DIFF = 3;
  static const int DICT = 4;
  static const int SPARSE = 5;

  static final Set<int> VALID_VALUES = new Set.from([
    NONE
    , FIXED
    , RL
    , DIFF
    , DICT
    , SPARSE
  ]);
  static final Map<int, String> VALUES_TO_NAMES = {
    NONE: 'NONE'
    , FIXED: 'FIXED'
    , RL: 'RL'
    , DIFF: 'DIFF'
    , DICT: 'DICT'
    , SPARSE: 'SPARSE'
  };
}
