/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
library mapd.src.t_execute_mode;

class TExecuteMode {
  static const int HYBRID = 0;
  static const int GPU = 1;
  static const int CPU = 2;

  static final Set<int> VALID_VALUES = new Set.from([
    HYBRID
    , GPU
    , CPU
  ]);
  static final Map<int, String> VALUES_TO_NAMES = {
    HYBRID: 'HYBRID'
    , GPU: 'GPU'
    , CPU: 'CPU'
  };
}
