/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
library mapd.src.t_expression_range_type;

class TExpressionRangeType {
  static const int INVALID = 0;
  static const int INTEGER = 1;
  static const int FLOAT = 2;
  static const int DOUBLE = 3;

  static final Set<int> VALID_VALUES = new Set.from([
    INVALID
    , INTEGER
    , FLOAT
    , DOUBLE
  ]);
  static final Map<int, String> VALUES_TO_NAMES = {
    INVALID: 'INVALID'
    , INTEGER: 'INTEGER'
    , FLOAT: 'FLOAT'
    , DOUBLE: 'DOUBLE'
  };
}
