/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
library mapd.src.t_map_d_exception;

import 'dart:typed_data' show Uint8List;
import 'package:thrift/thrift.dart';
import '../mapd.dart';

class TMapDException extends Error implements TBase {
  static final TStruct _STRUCT_DESC = new TStruct("TMapDException");
  static final TField _ERROR_MSG_FIELD_DESC = new TField("error_msg", TType.STRING, 1);

  String _error_msg;
  static const int ERROR_MSG = 1;


  TMapDException() {
  }

  // error_msg
  String get error_msg => this._error_msg;

  set error_msg(String error_msg) {
    this._error_msg = error_msg;
  }

  bool isSetError_msg() => this.error_msg != null;

  unsetError_msg() {
    this.error_msg = null;
  }

  getFieldValue(int fieldID) {
    switch (fieldID) {
      case ERROR_MSG:
        return this.error_msg;
      default:
        throw new ArgumentError("Field $fieldID doesn't exist!");
    }
  }

  setFieldValue(int fieldID, Object value) {
    switch (fieldID) {
      case ERROR_MSG:
        if (value == null) {
          unsetError_msg();
        } else {
          this.error_msg = value;
        }
        break;

      default:
        throw new ArgumentError("Field $fieldID doesn't exist!");
    }
  }

  // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
  bool isSet(int fieldID) {
    switch (fieldID) {
      case ERROR_MSG:
        return isSetError_msg();
      default:
        throw new ArgumentError("Field $fieldID doesn't exist!");
    }
  }

  read(TProtocol iprot) {
    TField field;
    iprot.readStructBegin();
    while (true) {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) {
        break;
      }
      switch (field.id) {
        case ERROR_MSG:
          if (field.type == TType.STRING) {
            this.error_msg = iprot.readString();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  write(TProtocol oprot) {
    validate();

    oprot.writeStructBegin(_STRUCT_DESC);
    if (this.error_msg != null) {
      oprot.writeFieldBegin(_ERROR_MSG_FIELD_DESC);
      oprot.writeString(this.error_msg);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  String toString() {
    StringBuffer ret = new StringBuffer("TMapDException(");

    ret.write("error_msg:");
    if (this.error_msg == null) {
      ret.write("null");
    } else {
      ret.write(this.error_msg);
    }

    ret.write(")");

    return ret.toString();
  }

  validate() {
    // check for required fields
    // check that fields of type enum have valid values
  }

}

