/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
library mapd.src.t_merge_type;

class TMergeType {
  static const int UNION = 0;
  static const int REDUCE = 1;

  static final Set<int> VALID_VALUES = new Set.from([
    UNION
    , REDUCE
  ]);
  static final Map<int, String> VALUES_TO_NAMES = {
    UNION: 'UNION'
    , REDUCE: 'REDUCE'
  };
}
