/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
library mapd.src.t_table_type;

class TTableType {
  static const int DELIMITED = 0;
  static const int POLYGON = 1;

  static final Set<int> VALID_VALUES = new Set.from([
    DELIMITED
    , POLYGON
  ]);
  static final Map<int, String> VALUES_TO_NAMES = {
    DELIMITED: 'DELIMITED'
    , POLYGON: 'POLYGON'
  };
}
