description: "MapD driver for Dart. Works both on server and in browser"
name: "mapd"
version: "0.0.1"
dependencies:
  fixnum: "^0.10.2"
  http: "^0.11.3"
  logging: "^0.11.0"
dev_dependencies:
  test: "^0.12.0"
  browser: "any"
  mockito: "^1.0.0"
environment:
  sdk: ">=1.20.1 <2.0.0"
