description: "A sample command-line application."
name: "mapd"
version: "0.0.1"
dependencies:
  http: "any"
  logging: "any"
  logging_handlers: "any"
  thrift:
    git:
      ref: "6462b664aa6eb796135325dc11080aa0d8ab1184"
      url: "https://bitbucket.org/iv_framework/thrift.git"
dev_dependencies:
  test: "^0.12.0"
  browser: "any"
environment:
  sdk: ">=1.20.1 <2.0.0"
